default_stages: [commit]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [
          --fix, 
          --ignore=E402,
          --line-length=79, 
        ]

      # Run the formatter.
      - id: ruff-format
        args: [
          --line-length=79
      ]
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        verbose: True
        args:
          - -vv
          - --fail-under=0      
  # - repo: https://github.com/psf/black
  #   rev: 22.12.0
  #   hooks:
  #   - id: black
  #     args: [
  #       --line-length=79, 
  #       --target-version=py38
  #     ]
  #     exclude: ^(venv/|docs/)
  #     types: ['python']
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.0.0
  #   hooks:
  #   - id: flake8
  #     args: [
  #       --max-complexity=20,
  #       --ignore=E402, # top level import library
  #       --extend-ignore=W503 # starting line with line break
  #     ]
  #     exclude: ^(venv/|docs/)
  #     types: ['python']
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       args: [
  #         --profile=black
  #       ]
